[package]
name = "tutorials"
version = "0.1.0"

[addresses]
TicketTutorial = "9b0a2b8dbf5ccadd1fd96b84b8bb9ff7"
AptosFramework = "0x1" # Specify and assign 0x1 to the named address "Std"

[dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework" }
MoveNursery = { local = "../../aptos-core/aptos-move/framework/move-stdlib/nursery" }
